# Generated by Django 4.0.1 on 2022-01-13 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=40)),
                ('creation_time', models.DateTimeField(auto_now_add=True, help_text='Start time')),
                ('completion_time', models.DateTimeField(help_text='End time', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(help_text='Title the activity', max_length=40)),
                ('description', models.TextField(help_text='More information on activity to partake')),
                ('time_estimate', models.IntegerField(help_text='Time in hours required to compelete activity')),
                ('completed', models.BooleanField(default=False, help_text='Task completion status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectp.project')),
            ],
        ),
    ]
